Backendapi
attilaDora/capstone pull request #39
Opened 2022-05-23 15:16 UTC by attilaDora

Backend built and connected to the db.

2022-05-23 16:08 UTC, matthias-hiemer requested changes
Die Tests sind noch nicht lauffähig :) 
Das sollte gelöst werden, wenn du einen Dummy API Key in den Test application.properties definierst.

2022-05-23 16:44 UTC, vangoh74 commented on backend/src/main/java/de/neuefische/backend/BackendApplication.java
> +
Die Zeile würde ich löschen

2022-05-23 16:44 UTC, vangoh74 commented on backend/src/main/java/de/neuefische/backend/BackendApplication.java
> +
Die obere zwei Zeilen würde ich löschen!

2022-05-23 17:01 UTC, vangoh74 commented on backend/src/main/java/de/neuefische/backend/BackendApplication.java
> +
Die Zeile würde ich entfernen!

2022-05-23 17:01 UTC, vangoh74 commented on backend/src/main/java/de/neuefische/backend/BackendApplication.java
> +
Die Zeilen 14 und 15 auch!

2022-05-23 17:04 UTC, vangoh74 approved these changes
Das meisten war schon reviewed! Für mich sieht es ok aus!

2022-05-24 10:26 UTC, Flooooooooooorian reviewed
Zwei kleine Anmerkungen noch, sonst sieht es aber gut aus 👍

2022-05-24 10:26 UTC, Flooooooooooorian commented on backend/src/main/java/de/neuefische/backend/model/Cocktail.java
> +    String imageURL;
```suggestion
    String imageUrl;
```

2022-05-24 10:26 UTC, Flooooooooooorian commented on backend/src/main/java/de/neuefische/backend/WebClientConfig.java
> +}
Ich würde bei der @ Bean Variante, die wir im Kurs gemacht haben bleiben. Für die Tests machen wir ja morgen noch eine kleine Session.

2022-05-24 10:51 UTC, merged